### ISSUE TITLE
support for hosting audio files on an external server

### ISSUE THREAD

**Issue by funkenstrahlen** [jekyll-octopod/jekyll-octopod#10]
I host my audio files on Podseed. Currently Octopod assumes all my audio files are located in the `episodes` directory. Is there a way to change this baseurl (e.g. in config.yml), so it can link to an external audio file source?

**Comment by haslinger** [comment]
Currently changing baseurl wouldn't help. We can add this as a feature request.

**Comment by haslinger** [comment]
Regarding Podseed: Is it reasonable to assume, that all podcast audio files live in the same dir?

**Comment by funkenstrahlen** [comment]
> Regarding Podseed: Is it reasonable to assume, that all podcast audio files live in the same dir?

Yes.

This is an example url from my podcast: `http://cdn.podseed.org/funkenstrahlen/fs089-minecraft-eine-welt-voller-abenteuer.m4a`

**Comment by haslinger** [comment]
Resolved by https://github.com/jekyll-octopod/jekyll-octopod/commit/d9c5496d6c9cb54a609e81d616edcf219390aa89, use download_url in your config for the path to your episodes.
