### ISSUE TITLE
template has no `poster`, `logo` and `audio` binding

### ISSUE THREAD

**Issue by mibamur** [jekyll-octopod/jekyll-octopod#12]
We should able to do it

**Comment by haslinger** [comment]
Sorry for taking so much time to answer. I'm not fully sure, what you mean here:
The theme is now extracted and has it's own Gem: https://github.com/jekyll-octopod/jekyll-bootflat

I completely don't get, what you mean with poster, binding and template in this context. Please elaborate a bit more.

**Comment by haslinger** [comment]
Feel free to follow up on this and reopen , meanwhile I close the issue.
