### ISSUE TITLE
bug?: keine Episoden im feed

### ISSUE THREAD

**Issue by Dorifer** [jekyll-octopod/jekyll-octopod#13]
bei einer bestehenden octopod installation läuft der build prozess sauber durch, bei der fertigen seite sind die rss feeds aber leer (https://1mpa.chaostreff.at) die direkten downloads bei der episode & der web player funktionieren normal.

**Comment by haslinger** [comment]
Ich verstehe Deine Meldung nicht. 
Die beiden Feeds beinhalten jeweils die Episode.

**Comment by Dorifer** [comment]
bei mir wird im ff kein feed-inhalt angezeigt (siehe screenshot), mein podcatcher beschwert sich ebenfalls.
![screenshot](https://cloud.githubusercontent.com/assets/1337087/16546154/067c7c68-4142-11e6-86b1-55bbcdbb64ba.png)

**Comment by haslinger** [comment]
Feed validator meint, ein & ist keine gute Idee im Autor: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2F1mpa.chaostreff.at%2Fepisodes.ogg.rss sonst keine Probleme.

Im Beyondpod sehe ich einen SSL-Handshake Error.

**Comment by Dorifer** [comment]
das & war tatsächlich das Problem. feed ist valide & wird überall korrekt angezeigt. Danke für die HIlfe
