### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by haslinger** [jekyll-octopod/jekyll-octopod#14]
Tags would be nice:
- Tagging episodes
- Tag list -> Tag episode page

**Comment by pattex** [comment]
I wrote a plugin for this a while ago. It's a bit rusty but I look after it since a few days.
https://github.com/pattex/jekyll-tagging

**Comment by haslinger** [comment]
Thanks for your comment! (and the plugin)
I actually know of it and tried it already, but I will have to extend it, because it expects tags only to be used in episodes (and I have users calling for tags on other collections already...) :-)

**Comment by haslinger** [comment]
User, who requested this, doesn't use jekyll-octopod any more ;-(
