### ISSUE TITLE
Octopod trying to find configuration from hardcoded path in executable

### ISSUE THREAD

**Issue by johnkpaul** [jekyll-octopod/jekyll-octopod#17]
https://github.com/jekyll-octopod/jekyll-octopod/blob/master/bin/octopod#L5

I was unable to `octopad setup` until changing this line directly inside of the gem. I uncommented line 5 and commented line 4.

**Comment by johnkpaul** [comment]
If that's the intended fix, just let me know and I can open a PR. 

Thanks for putting this together! I am already finding it useful.

**Comment by haslinger** [comment]
This ugly hack for easier development should have never made it in the code base, sorry!
And thanks for pointing it out to me.
No need for a PR, new version 0.7.5 is pushed to Rubygems as well.

Happy to hear, that you find it useful, but most of the work was done by @pattex, so thank him ;-)

**Comment by johnkpaul** [comment]
:) Thanks @pattex! Glad this was updated and released so quickly.
