### ISSUE TITLE
Missing linking back and forth between repo and Github page

### ISSUE THREAD

**Issue by klappradla** [jekyll-octopod/jekyll-octopod#2]
I am missing a link to the Github repository when browsing the Github page (which in itself is awesome). Maybe add a link to the navigation such as [React](https://facebook.github.io/react/) has it, or in the footer section, such as [Bootflat](http://bootflat.github.io/) has it. I'd personally prefer the first approach, since the navigation is in place anyways and could easily host another item.

Furthermore, but that's sugar: you could extend the title on Github _("Podcast publishing extension for Jekyll")_ with the link to the Github page. Again, same as [React has it](https://github.com/facebook/react)

**Comment by haslinger** [comment]
Thanks for the suggestions! (Easier for me to get to the issues as well :-) )
The nav column on the right is a more natural place than the bottom. So I put one there as well.

**Comment by klappradla** [comment]
Well, you know have it in the navbar twice. Was that intended? Looks kind of weird on mobile with the hamburger menu though...

**Comment by haslinger** [comment]
It was on purpose, will probably change some things around after the workshop tomorrow anyways ...

**Comment by haslinger** [comment]
I had the feeling, that the lonely link on the top was a bit lost, but the second one was weird, as you pointed out. 
I believe, the solution, I came up with (issues and repo link) now, fits my goal to be visible, useful and not weird.
