### ISSUE TITLE
HTML Encoded feed isn't valid

### ISSUE THREAD

**Issue by pathetiq** [jekyll-octopod/jekyll-octopod#20]
Hi,

RSS feed with encoded characters like French word "`Décembre`" HTML encoded like " `D&eacute;cembre`" will make an error when validating the feed ([https://validator.w3.org/feed/check.cgi](https://validator.w3.org/feed/check.cgi)).

The feed generation file would need to HTML unencoded the value before printing the value.

I will see if I can have a fix quick, but if you can help that would be awesome.

Thanks to support this project!

**Comment by haslinger** [comment]
Interesting, I don't see errors or warnings for &amp; in links in my feeds. But why would you include them HTML encoded in the first place instead of inserting the Unicode characters?

Are you expecting users with legacy browsers not capable of displaying Unicode characters?

**Comment by pathetiq** [comment]
Officially the bug I have on my jekyll setup is that without my config encoded in the _config.yml the _config.yml file will cause problem and not compile at jekyll level. I don't own the server so right now I don't have exact logs, but I'll ask.

Also have the problem to validate the XML with the `&` in a tag like this: ` <psc:chapter start="00:48:14.000" title="Outro & Shameless plugs" />` but is fixed with `&amp;` ([Related to this](https://validator.w3.org/feed/docs/error/SAXError.html))

See the errors for yourself [here](https://securite.fm/episodes.mp3.rss) and let me know if maybe something else is wrong?

Thanks again

**Comment by haslinger** [comment]
Ah I see, so now I tried with Sécurité sans frontières (Unicode) in my podcast as subtitle.

Compiled without any issues, see screenshot of the sidebar, where the subtitle is displayed: 

![subtitle](https://cloud.githubusercontent.com/assets/1116624/21730921/43d879f6-d452-11e6-8284-e1a00992585d.png)

**Comment by pathetiq** [comment]
Will verify no idea why it would block on my side

**Comment by haslinger** [comment]
Sure :-)

![verified](https://cloud.githubusercontent.com/assets/1116624/21731321/1bf61432-d454-11e6-871d-1a33325eaa93.png)

**Comment by haslinger** [comment]
No follow ups for > 3 weeks, so I guess it's sorted out.
