### ISSUE TITLE
SyntaxError during octopod serve

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [jekyll-octopod/jekyll-octopod#22]
I was following the instructions on the octopod site to get a development instance running, when I encountered the following error message:

/var/lib/gems/2.3.0/gems/jekyll-octopod-0.7.5/bin/octopod:272:in `load': /var/lib/gems/2.3.0/gems/jekyll-octopod-0.7.5/lib/jekyll/static_file.rb:9: syntax error, unexpected ')', expecting keyword_end (SyntaxError)
/var/lib/gems/2.3.0/gems/jekyll-octopod-0.7.5/lib/jekyll/static_file.rb:20: syntax error, unexpected end-of-input, expecting keyword_end
	from /var/lib/gems/2.3.0/gems/jekyll-octopod-0.7.5/bin/octopod:272:in `<top (required)>'
	from /usr/local/bin/octopod:23:in `load'
	from /usr/local/bin/octopod:23:in `<main>'

I'm on Xubuntu 16.10 using ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu] and gem 2.5.1.

I'll try taking a look at the file myself, but I have no idea about ruby.

**Comment by MyrionPhoenixmoon** [comment]
So I removed what looked like an extraneous ')' on line twenty in the static_file.rb file.

Now I get: jekyll 3.3.1 | Error:  undefined method `write' for class `Jekyll::StaticFile'.

**Comment by MyrionPhoenixmoon** [comment]
I figured out that that's probably because alias_method is accessing ```write``` before ```def write```.

Now there's an argument mismatch somewhere. ```Error:  wrong number of arguments (given 4, expected 0)```

Unfortunately, this one doesn't tell me where, so I'm stuck.

**Comment by haslinger** [comment]
First: Nice to meet you again :-)

Thanks for your bug report. I can confirm the bug, fixed it like you and created a new test site (and saw two more bugs, that I fixed), but nothing regarding your second error, just css stuff and requiring css files. 
Accessing something below is no problem, worked for years and also with my ruby 2.3.2p217.

Let's try this: 
Please delete your project and start all over again (sorry for that).

Update your Gemfile by just adding one line at the end to require the current version, that I just created (and keep all the generated stuff in):
`gem 'jekyll-octopod', '0.7.7'`

I further more learned, that current Jekyll creates an extra index.md in the app dir, please delete this as well, it is the old index.html that we depend on. (You can rename this to index.md, if you like, but that doesn't matter)

Does this help?

**Comment by MyrionPhoenixmoon** [comment]
Same here :)

I tried making it useful, so I'm glad to see you could replicate the error.

I started over and now the Gemfile already has some content from Jekyll, so instead of deleting all of it and replacing it with the two lines from the octopod docs, I just added the line ```gem 'jekyll-octopod', '0.7.7'``` where it told me to put plugins.

That did install octopod, and octopod setup worked, but octopod serve got me this:
```
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jekyll-octopod'. (Bundler::GemRequireError)
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `each'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `block in require'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:61:in `each'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:61:in `require'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:99:in `require'
	from /var/lib/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler'
	from /var/lib/gems/2.3.0/gems/jekyll-3.3.1/exe/jekyll:9:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/jekyll-octopod-0.7.7/bin/octopod:272:in `load'
	from /var/lib/gems/2.3.0/gems/jekyll-octopod-0.7.7/bin/octopod:272:in `<top (required)>'
	from /usr/local/bin/octopod:23:in `load'
	from /usr/local/bin/octopod:23:in `<main>'
```

**Comment by haslinger** [comment]
I am meanwhile quite sure, there is an issue with your ruby installation. As far as I see from the paths, you are using ruby that comes with Ubuntu. I ditched that seven years ago, when they only provided super old versions, but that's a different story.

For your user - ignore system ruby (or even uninstall it, if you only use it for this particular project) and go with RVM: https://rvm.io/
RVM installs a user specific, switchable full blown installation in a .rvm dir in your user account with the two line install given on their site.
I'm not sure, if Xubuntu comes with it's own weird named terminal app. If so and after the install if openening a new terminal and entering
`type rvm | head -n1`
results not in 
`rvm is a fuction`
(which would indicate, that it's properly loaded), add an extra 
`source /home/%USER%/.rvm/scripts/rvm`
where your insert your user name to load it properly. Restart the terminal and check for
`rvm is a fuction`

As written above, I'm using the RVM approach now on all my environment machines and server vm's and it just works.

**Comment by MyrionPhoenixmoon** [comment]
I'm using Zsh, if that matters, either through Terminal or guake-terminal.

I installed RVM, and got this result:
```rvm is /home/<UserName>/.rvm/bin/rvm```

So, that wasn't what you said it should be and therefore I sourced rvm:
```rvm is a shell function from /home/<UserName>/.rvm/scripts/cli```

Sourcing produces this output:
```
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /home/<UserName>/<folder>/podcast-site/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

Unknown ruby interpreter version (do not know how to handle): RUBY_VERSION.
```

In both cases, I still get the ```'rescue in block in require'``` error.

**Comment by haslinger** [comment]
let's ignore the warnings for a start.
The 'rescue in block in require' should now fire for a different file, right?
`/home/%username%/.rvm/rubies/ruby-2.3.2/bin/ruby/bundler/runtime.rb` or similar.

Now please try 
`jekyll serve `
instead of 
`octopod serve`

For the 'serve' directive octopod is only a wrapper for jekyll anyways.

**Comment by MyrionPhoenixmoon** [comment]
No, it still uses the old file, and the old ruby, I suspect. I can't uninstall that, as it's required by texlive.

Edit: Installing ruby through rvm changed it though, now it breaks on 
```
from /home/username/.rvm/gems/ruby-2.3.3/gems/jekyll-3.3.1/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler'
from /home/username/.rvm/gems/ruby-2.3.3/gems/jekyll-3.3.1/exe/jekyll:9:in `<top (required)>'

```


The jekyll command had the same output.

**Comment by MyrionPhoenixmoon** [comment]
I double-checked and was able to uninstall ruby. Texlive only recommends it, but does not require it.

I had to install bundler, octopod and jekyll again, to update them to the new paths, it seems.
Then I had to reinstall ruby-2.3.3 through rvm, to get libruby.so again, but now it works. YAY!

**Comment by MyrionPhoenixmoon** [comment]
Though I can't help but wonder how I could've solved this if I'd needed the apt-provided ruby package...

**Comment by haslinger** [comment]
Awesome!

That actually would be 'easy': Create an extra user just for rvm, let that user use rvm.
But you had to switch to that user, each time you need Jekyll....
