### ISSUE TITLE
Documentation: How to Change a Theme

### ISSUE THREAD

**Issue by haslinger** [jekyll-octopod/jekyll-octopod#23]
build upon:

Du findest das verwendete Thema unter:
https://github.com/jekyll-octopod/jekyll-bootflat
es basiert auf Bootstrap und nennt sich Bootflat.

Seine Dokumentation ist unter: http://bootflat.github.io/

Die Anpassung erfolgt am besten durch Überschreiben der
Variablen, die in den Files in
https://github.com/jekyll-octopod/jekyll-bootflat/tree/master/_sass/bootflat
sind, dazu das entsprechende File nach
/sitedir/_sass/bootflat/
kopieren und modifizieren oder eine zentrale
/sitedir/_sass/_overrides.scss
anlegen und diese verwenden.

Analog lassen sich alle Variablen, die Bootflat nicht überschreibt,
in den Bootstrap-sass files aus
https://github.com/jekyll-octopod/jekyll-bootflat/tree/master/_sass/bootstrap
nach dem gleichen Prinzip in
/sitedir/_sass/bootstrap/
oder auch wieder in overrides überschreiben

Wenn das jetzt wirr klang, lies vielleicht:
https://github.com/jekyll-octopod/jekyll-bootflat/blob/master/assets/css/main.scss
da siehst du die Import-Reihenfolge und verstehst warum "overrides"
immer gewinnt.

**Comment by MyrionPhoenixmoon** [comment]
So, currently we have some documentation in the sass files themselves.

Documenting all the variables can't really be our job, as we'd go out of date really quick. Do we really need more than a good sample file (and reference to it)?

**Comment by haslinger** [comment]
People who want to change the css have to change css files -> Yes pointing to your nice example is enough.

**Comment by haslinger** [comment]
You actually can use the scss variables after inlining them into the project:
I now wrote a [page on theming](https://jekyll-octopod.github.io/theming) for the project site.
