### ISSUE TITLE
Color schemes

### ISSUE THREAD

**Issue by haslinger** [jekyll-octopod/jekyll-octopod#24]
find a way, how color schemes can be contributed.

**Comment by haslinger** [comment]
@MyrionPhoenixmoon as a first step let's add your color scheme commented in  https://github.com/jekyll-octopod/jekyll-octopod/blob/master/assets/_sass/_overrides.scss

Then the only step to use it is to uncomment it in the file (the setup script copies it in the actual project).

Update: Hah - you started to it that way already. Great!

**Comment by MyrionPhoenixmoon** [comment]
I've had an idea how we could do themes easily:

Using import statements. (Too obvious to think of, right?)

In the _sass folder, we could have subfolders for each theme, like so: 
```
_sass/
    swiss/
        swiss.scss
    dark/
        dark.scss
```

Enabling a theme is then just a matter of adding an import. ```@import 'swiss/swiss' ``` for example.
Any theme could be split up into multiple files, with the folder and the "main" file being named as the theme. The main file would then pull in any further files.

Distribution of themes could be done through a git repo, where you can download each theme as a .zip folder, or simply by including them in the main repo. They're simply text files, so it's not like it's gonna blow up the size of the source until we've got thousands of themes.

What do you think?

**Comment by haslinger** [comment]
My first thought was, having a separate directory per theme is over engineered, but meanwhile I think, it's fine. Go for it -> make it a PR!

**Comment by MyrionPhoenixmoon** [comment]
Yeah, I was thinking about just having a file per theme, but it really costs us nothing to have a folder per theme, and it keeps it clean if someone wants to split a theme into multiple files.

I'll get on that pull request this weekend, I hope :)
