### ISSUE TITLE
Feed generation is broken

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [jekyll-octopod/jekyll-octopod#30]
In feed.xml on line 44, page.page_number is unset, and thus the episodes are never included in the feed.

I'm investigating where this number would be from.

**Comment by haslinger** [comment]
1. it is set by https://github.com/jekyll-octopod/jekyll-octopod/blob/master/lib/jekyll/paged_feed_page_generator.rb#L12
2. line 44 doesn't contain it, old version of code?

**Comment by MyrionPhoenixmoon** [comment]
1. Where would I find this file to check if I have the correct version? I did gem update jekyll-octopod, but I'm not sure that worked. ```octopod --version``` displays ```jekyll 3.3.1```.

2. Old version of feed.xml. Apparently stuff got changed since I did octopod setup. Perhaps there should be some way to update that?

**Comment by haslinger** [comment]
1. You find the version currently used by a project in it's Gemfile.lock file. 
2. Pull requests welcome :-) Overwrite would be easy, but merging templates ... 

But in your case updating the Gem should suffice: `bundle update jekyll-octopod` run from your app dir.
gem update only installs it, but doesn't introduce it in any projects.

Edit: typo fixed, jekyll-octopod, not gem-octopod. Tired already...

**Comment by haslinger** [comment]
Btw., I forgot: You can  `octopod setup` to update the files. It asks you file by file, if you want to overwrite, but that's a pain...

**Comment by MyrionPhoenixmoon** [comment]
Aha! Yes, that seems to be it - Gemfile.lock lists 0.7.7, which doesn't, in fact, include page_number. So did the gemfile. I had to manually update the Gemfile, ```bundle update jekyll-octopod``` did not update the gemfile.

Changing the Gemfile gave me octopod 0.8.3, but also introduced an Error:
```uninitialized constant Jekyll::Octopod in /_layouts/feed.xml```

**Comment by MyrionPhoenixmoon** [comment]
And once I know what's wrong, I'll try to open an appropriate pull request :)

**Comment by MyrionPhoenixmoon** [comment]
Okay, the error (which I found through ```jekyll serve -t```, which displays the full stacktrace) is in octopod_filters.rb line 299. In the version_string method, JEKYLL::OCTOPOD is not defined, apparently.

Hacking that out fixes the error and correctly generates the feed.

**Comment by MyrionPhoenixmoon** [comment]
Hmpf, my _config.yml got overwritten despite declining to overwrite it during ```octopod setup```.

**Comment by haslinger** [comment]
Jekyll::Octopod::VERSION comes via  https://github.com/jekyll-octopod/jekyll-octopod/blob/master/lib/octopod/version.rb - don't get the problem currently ... hmmm.....

**Comment by haslinger** [comment]
Got it! That error is fixed with 0.8.3. But there is a new one with Jekyll 3.4.0 now ...

**Comment by MyrionPhoenixmoon** [comment]
I am on 0.8.3, though...

And Jekyll 3.3.1.

**Comment by haslinger** [comment]
Sorry: 0.8.5 (just released) fixes it.

**Comment by haslinger** [comment]
Ok and 0.8.6 is compatible with Jekyll 3.4.0. :-)
What a mess!

**Comment by MyrionPhoenixmoon** [comment]
It rather was. Why do you think that changed?

Anyway, glad it's fixed now and my podcast experimentally works in Thunderbird and iTunes, with correct pictures and all ;)

**Comment by haslinger** [comment]
Several things came together. I learned: Local mounting of Gems requires files differently. During development I load the Gem via:
`gem 'jekyll-octopod', path: "../jekyll-octopod"`
not to have to create a new version for each change and test and then I don't have to require the version file, as it's required by the gemspec file.

The latest version of the feed contains the version for specifying a generator string including the version of Jekyll Octopod (and lot's of other new tags, like an image on episode level). That caused the original error.

And then via Jekyll 3.4 stuff, that had a (not shown since 2014!) deprecation warning before, suddenly was an error.

Well at least we make progress > 30 commits this year already!

**Comment by MyrionPhoenixmoon** [comment]
Oh, that sounds both annoying and pretty great. 

Looks like the documentation really needs an update, too, images per episode isn't in there yet, right?
I'll see if there's anything I can help with.
