### ISSUE TITLE
Missing assets, deploy errors

### ISSUE THREAD

**Issue by toby3d** [jekyll-octopod/jekyll-octopod#31]
To repeat the errors, you need to do the following:
- Create a new Jekyll project with a clean Octopod from scratch
- If necessary, specify your own domain / subdomain through the CNAME file
- Change the endpoint in the configuration file
- Deploy in Github Pages

# Errors:
- `Your site is having problems building: The tag podigee_player on line 1 in _posts/2016-03-22-episode0.md is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.`  
_For skip, I changed `{% podigee_player page %}` to `{{ podigee_player page }}`._
- `Your site is having problems building: A file was included in about.md that is a symlink or does not exist in your _includes directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink/.`  
_For skip, I just remove all `{% include icon-github.html username="jekyll" %}` blocks._
- **Missing all assets and "subscribe" button error**  
_You can see problems [here](https://podcast.toby3d.ru)._

**Comment by haslinger** [comment]
I was just recreating a new site from scratch and everything worked fine.
Did you follow the Installation procedure? https://jekyll-octopod.github.io/installation
When is the first error occuring? What are your Ruby Version, Jekyll Version, jekyll-octopod versions?

Are you aware, that to use arbitrary Gems like jekyll-octopod with Github Pages, you have to create the site locally and deploy the results yourself?

**Comment by toby3d** [comment]
> Did you follow the Installation procedure?

Yep.

> When is the first error occuring?

After sending the content after the `octopod setup`.

> What are your Ruby Version, Jekyll Version, jekyll-octopod versions?

Ruby: `ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux-gnu]`
Jekyll: `jekyll 3.4.2`
Octopod: `jekyll-octopod (0.8.7)`

> Are you aware, that to use arbitrary Gems like jekyll-octopod with Github Pages, you have to create the site locally and deploy the results yourself?

I know what I did. You can see the results here (after solving the first two errors): https://github.com/toby3d/podcast

**Comment by haslinger** [comment]
- Regarding the first error: Go back to the original syntax: {% podigee_player page %}, it was correct. podigee_player is a tag.

- Regarding the second one: Now I see, as your version of Jekyll already creates a Gemfile itself, just add the line 
```gem 'jekyll-octopod'```
instead of replacing the already existing content of the Gemfile.

- bundle one more time and check the creation of the assets in your local _site directory after `jekyll serve` or `jekyll build`. Then you should be ready to deploy.

**Comment by toby3d** [comment]
> ...just add the line `gem 'jekyll-octopod'` instead of replacing the already existing content of the Gemfile.

[Already done.](https://github.com/toby3d/podcast/blob/master/Gemfile)

>Then you should be ready to deploy.

Locally - everything is fine. Assets are lost after deploy and Github Pages reports errors.

**Comment by haslinger** [comment]
Where is the repo and/or the branch, you pushed the generated _site dir to?

**Comment by toby3d** [comment]
I remove `.gitignore` line and push _site folder [in another branch](https://github.com/toby3d/podcast/tree/develop/_site).

**Comment by haslinger** [comment]
You cannot publish to github-pages from any random branch, see their guides for it: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

That's why I asked:
> Are you aware, that to use arbitrary Gems like jekyll-octopod with Github Pages, you have to create the site locally and deploy the results yourself?

As you've spoiled the master branch for the app itself, if you want the github page to be served from the repo, it needs to live inside the branch gh-pages. Then you also have to set branch in the project config to pick it up. (see Github's guide linked above for this as well).

**Comment by toby3d** [comment]
> You cannot publish to github-pages from any random branch

I know. I put the contents in a separate branch so you can make sure that the paths to the assets are all right, but they are not. By default, the `_site` directory is generated on the github side and it should NOT be contained in the repository.

> As you've spoiled the master branch for the app itself, if you want the github page to be served from the repo, it needs to live inside gh-pages.

GitHub Pages works with the `master` and `gh-pages` branches and the `docs` directory in `master`. I'm working with the `master` branch, since this repository is entirely intended to be in GitHub Pages.

**Comment by haslinger** [comment]
There is no jekyll-octopod issue here. You have a misunderstanding of GitHub Pages.
**GitHub Pages webhooks do not allow arbitrary gems in their Gemfile, they are simply ignored.** 

To use arbitrary Gems like jekyll-octopod with Github Pages, you have to create the site locally and deploy the results, that have been created in the _site directory to a master branch of a different project or to the gh-pages_branch of the same project yourself.

Update: Here is the Jekyll documentation I am refering to regarding the use of Gems/Plugins https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
