### ISSUE TITLE
Octopod doesn't generate feeds anymore

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [jekyll-octopod/jekyll-octopod#34]
So I switched to a new device and set up octopod there to continue working on my podcast. Unfortunately, it seems that (without me changing the _config.yml file) Octopod has stopped generating my RSS feed, leading to the Subscribe button complaining about no feeds being present.

How do I convince Octopod of generating RSS-Feeds again?

**Comment by MyrionPhoenixmoon** [comment]
Update with correction:

The feed is generated - but it is not passed to the subscribe button, as it is not listed in site['episode_feed_formats'].

I manually had to add 
```json
          {
		"type": "audio",
          	"format": "mp3",
          	"url": "https://swiss-sided-dice.ch/feed.rss",
          	"variant": "high"
	  }
```
to every instance of the subscribe button.

**Comment by haslinger** [comment]
The feeds are created by files with names like `episodes.mp3.rss` in the same dir as _config.yml
that contain just a bit of code
```
---
layout: feed
format: mp3
---
{{ content }}
```
Maybe you lost them with the relocation?

**Comment by MyrionPhoenixmoon** [comment]
Oh, that must be the case. 

Let me try that out.

**Comment by MyrionPhoenixmoon** [comment]
Yes, that was the fix.

My .gitignore ignored .rss files because those are generally only generated. 

Thank you!
