### ISSUE TITLE
Hiding chaptermarks

### ISSUE THREAD

**Issue by lucashowell** [jekyll-octopod/jekyll-octopod#41]
Is there an option to hide the chaptermarks from the podigee player to make it a more compact player?  Right now I get a *.map error if I don't have at least one chaptermark included.  

If the option doesn't exist, is it straightforward to add to the player jekyll tag?

**Comment by haslinger** [comment]
There is no option in the current implementation of jekyll-octopod. 

I would say, it is straight forward. Find their documentation at: https://github.com/podigee/podigee-podcast-player
Pull requests are welcome!

**Comment by markwk** [comment]
Agreed. Not sure why chapters are required. Getting a similar error and would make sense to them optional and to provide a flag to use compact version of podigree. Will try and dig into the code on this one.

**Comment by haslinger** [comment]
@kylemhall  Thank you!
-> Is now fixed in master.
-> Will hopefully create a new release next week (have to update some docs before)  and then close this issue here.

**Comment by haslinger** [comment]
Well no ;-) The changes in the docs are unrelated, so new version created and published: 0.9.4.
