### ISSUE TITLE
Error:  undefined method `write' for class `Jekyll::StaticFile'

### ISSUE THREAD

**Issue by ghost** [jekyll-octopod/jekyll-octopod#49]
I followed the instructions on setting up octopod "https://jekyll-octopod.github.io/installation" and this came out:

WARN: Unresolved specs during Gem::Specification.reset:
      multi_json (>= 0)
      listen (~> 3.0)
      rouge (< 4, >= 1.7)
      rb-inotify (>= 0.9.7, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/lib/ruby/vendor_ruby/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /mnt/c/ProgramData/Oracle/Java in PATH, mode 040777
Configuration file: /mnt/c/Users/rafaelg/Desktop/Projects/octopod/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
jekyll 3.7.3 | Error:  undefined method `write' for class `Jekyll::StaticFile'

does anyone know why am I getting that last 'write' method error?, how can I fix it?

**Comment by haslinger** [comment]
I believe nobody has ever used jekyll-octopod on Windows, so you are pioneering here ;-)
(you are using the linux subsystem here, right?)

Maybe do not 'install' jekyll-octopod, but 'steal' it from one of my podcasts, e.g. using the [demo
site](https://github.com/jekyll-octopod/jekyll-octopod.github.io.source) or my [Aua-Uff-Code Podcast](https://github.com/aua-uff-code/aua-uff-co.de). 

Just delete the existing posts and episode and go from there.
You need to copy in a _config.yml, use [_config.yml.sample](https://github.com/jekyll-octopod/jekyll-octopod/blob/master/assets/_config.yml.sample) as a starting point

**Comment by ghost** [comment]
haha, yeah I'm on the windows linux subsystem, I'm going to take a look at what you suggested, thanks, I really want to get this up and running, also I'm using the minimal mistakes theme currently, is it easy to integrate octopod with a different theme?

**Comment by haslinger** [comment]
The question is more the other way round: Does the theme to be integrated support all features, that jekyll-octopod expects to work, out of the box?

E.g.: Minimal mistakes has no clues about the Boostrap grid, or navigation. So I guess, if you rip out Bootflat (and Bootstrap), you have a bit of work to do. - But it's only two layouts, if I remember correctly.

Bootstrap and Bootflat would have a lot of config options.

See the comment in [_overrides.scss ](https://github.com/jekyll-octopod/jekyll-octopod/blob/725efb8dd5c46236c607f87ab64b913ac13cdc93/assets/_sass/_overrides.scss} for an example to override stuff. 

There, you can also use all Bootstrap options to override. (See the docs of Boostrap 3: https://getbootstrap.com/docs/3.3/customize/)
You can also look in the actual Bootflat sass code, how the hundreds of config options are set there: https://github.com/jekyll-octopod/jekyll-bootflat/tree/master/_sass/bootflat
The Bootflat documentation is here: https://bootflat.github.io/documentation.html

And you can always override all the stuff, as usual.

**Comment by ghost** [comment]
I will have a look at Bootflat, it's new to me maybe I will end up switching from minimal mistakes, thanks for the help

**Comment by ghost** [comment]
do you know why am I getting this after running Jekyll serve?

      Generating...
  Liquid Exception: no implicit conversion of nil into String in index.html
jekyll 3.8.0.pre.rc1 | Error:  no implicit conversion of nil into String

I cloned this repo:

https://github.com/jekyll-octopod/jekyll-octopod.github.io.source

**Comment by haslinger** [comment]
Which ruby version?
I wouldn't use a Jekyll pre release...

**Comment by haslinger** [comment]
Pull once more!
I updated and set the Ruby version and the Gem versions explicitly. Does this help?

**Comment by ghost** [comment]
I cloned the repo again and I got the same error:

      Generating...
  Liquid Exception: no implicit conversion of nil into String in index.html
jekyll 3.8.0.pre.rc1 | Error:  no implicit conversion of nil into String

I'm using ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by haslinger** [comment]
That's weird, the versions are now fixed in the [Gemfile](https://github.com/jekyll-octopod/jekyll-octopod.github.io.source/blob/master/Gemfile) to the latest stable Ruby 2.5 and Jekyll 3.7.3, which are known to work. 
Are you in the right directory?

**Comment by Rafael-Guzman** [comment]
thanks for the help, just a question, why on the Gemfile you have gem 'jekyll-octopod', path: "../jekyll-octopod", I've never specified a path on a gem, when I serve it, it says it doesnt find it:

The path `/mnt/c/Users/rafaelg/Desktop/Projects/jekyll-octopod` does not exist.

I'm serving this repo:

**Comment by ghost** [comment]
okay I just double checked again, I'm serving with: bundle exec jekyll serve and I got the same error:

Configuration file: /mnt/c/Users/rafaelg/Desktop/Projects/aua-uff-co.de/_config.yml
            Source: /mnt/c/Users/rafaelg/Desktop/Projects/aua-uff-co.de
       Destination: /mnt/c/Users/rafaelg/Desktop/Projects/aua-uff-co.de/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: no implicit conversion of nil into String in index.html
jekyll 3.8.0.pre.rc1 | Error:  no implicit conversion of nil into String

**Comment by haslinger** [comment]
The last time, I saw this error, there was an issue, where somebody broke the _config.yml to invalid json. 
You are using the unchanged version from the repo?

**Comment by ghost** [comment]
I copied the inside of the _config.yml.sample  to the one that came with the repo, and renamed it to _config.yml, I havent touched anything else... I did delete the posts

**Comment by haslinger** [comment]
Use the original one from the repo, ignore the .sample, and start modifying from there.

**Comment by ghost** [comment]
I've been playing with the config file but I'm still getting that message, I have another jekyll site and it serves fine, if you have any ideas let me know, thanks


 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: no implicit conversion of nil into String in index.html
jekyll 3.8.0.pre.rc1 | Error:  no implicit conversion of nil into String

**Comment by haslinger** [comment]
I still don't understand how you get messages from jekyll 3.8.0.pre.rc1, when jekyll 3.7.3 is enforced in the current [Gemfile](https://github.com/jekyll-octopod/jekyll-octopod.github.io.source/blob/master/Gemfile).

**Comment by ghost** [comment]
I think this is something to do with the gemfile and the jekyll version, this is my gem list:

 gem list jekyll

*** LOCAL GEMS ***

jekyll (3.7.3, 3.6.2, 3.0.1)
jekyll-admin (0.8.0, 0.4.1)
jekyll-algolia (1.3.2, 1.1.5)
jekyll-avatar (0.6.0, 0.5.0)
jekyll-bootflat (0.2.4)
jekyll-coffeescript (1.1.1, 1.0.2, 1.0.1)
jekyll-commonmark (1.2.0, 1.1.0)
jekyll-commonmark-ghpages (0.1.5)
jekyll-data (1.0.0)
jekyll-default-layout (0.1.4)
jekyll-feed (0.9.3, 0.9.2, 0.3.1)
jekyll-gist (1.5.0, 1.4.1, 1.1.0)
jekyll-github-metadata (2.9.4, 2.9.3)
jekyll-mentions (1.3.0, 1.2.0)
jekyll-octopod (0.9.4)
jekyll-optional-front-matter (0.3.0)
jekyll-paginate (1.1.0)
jekyll-readme-index (0.2.0)
jekyll-redirect-from (0.13.0, 0.12.1)
jekyll-relative-links (0.5.3, 0.5.2)
jekyll-remote-theme (0.2.3)
jekyll-sass-converter (1.5.2, 1.5.0, 1.3.0)
jekyll-seo-tag (2.4.0, 2.3.0)
jekyll-sitemap (1.2.0, 1.1.1)
jekyll-swiss (0.4.0)
jekyll-theme-architect (0.1.1, 0.1.0)
jekyll-theme-cayman (0.1.1, 0.1.0)
jekyll-theme-dinky (0.1.1, 0.1.0)
jekyll-theme-hacker (0.1.1, 0.1.0)
jekyll-theme-leap-day (0.1.1, 0.1.0)
jekyll-theme-merlot (0.1.1, 0.1.0)
jekyll-theme-midnight (0.1.1, 0.1.0)
jekyll-theme-minimal (0.1.1, 0.1.0)
jekyll-theme-modernist (0.1.1, 0.1.0)
jekyll-theme-primer (0.5.3, 0.5.2)
jekyll-theme-slate (0.1.1, 0.1.0)
jekyll-theme-tactile (0.1.1, 0.1.0)
jekyll-theme-time-machine (0.1.1, 0.1.0)
jekyll-titles-from-headings (0.5.1, 0.5.0)
jekyll-watch (2.0.0, 1.5.1, 1.3.0)
minimal-mistakes-jekyll (4.11.1, 4.10.1, 4.10.0)

and this is the error:

Incremental build: disabled. Enable with --incremental
Generating...
Liquid Exception: no implicit conversion of nil into String in index.html
jekyll 3.8.0.pre.rc1 | Error: no implicit conversion of nil into String

I dont understand neither why does it say "jekyll 3.8.0.pre.rc1 "

**Comment by ghost** [comment]
I removed the ", github: "jekyll/jekyll" from the gemfile and I got:


  Generating...
  Liquid Exception: no implicit conversion of nil into String in index.html
jekyll 3.7.3 | Error:  no implicit conversion of nil into String

 now it ran with jekyll 3.7.3 but I still got the error

**Comment by haslinger** [comment]
You are still using a different Gemfile than [Gemfile](https://github.com/jekyll-octopod/jekyll-octopod.github.io.source/blob/master/Gemfile).
github: "jekyll/jekyll" is not in there!

**Comment by ghost** [comment]
okay, I gotta fix a few things here, I have to install ruby version 2.5.0

**Comment by ghost** [comment]
I checked a few things on my ubuntu system. after that I was able to serve the repo jekyll-octopod.github.io.source but I'm still getting that error message from the the aua-uff-co.de repository: 

Configuration file: /mnt/c/Users/rafaelg/Desktop/Projects/aua-uff-co.de/_config.yml
            Source: /mnt/c/Users/rafaelg/Desktop/Projects/aua-uff-co.de
       Destination: /mnt/c/Users/rafaelg/Desktop/Projects/aua-uff-co.de/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: no implicit conversion of nil into String in index.html
jekyll 3.7.3 | Error:  no implicit conversion of nil into String

my gemfile looks like this:

source "https://rubygems.org"
ruby '2.5.0'

gem 'jekyll', "3.7.3"

group :jekyll_plugins do
   gem 'jekyll-octopod', "0.9.4"
#  gem 'jekyll-octopod', path: "../jekyll-octopod"
   gem "jekyll-feed", "~> 0.6"
   gem 'jekyll-bootflat'
end

and this is the config file: 

# You have to configure this ###################################################
title: jekyll - octopod
# You should configure this ####################################################
url: https://jekyll-octopod.github.io
subtitle: Static Site Podcast Publishing for Geeks
description: Static Site Podcast Publishing for Geeks.
author: Stefan Haslinger
email: stefan.haslinger@informatom.com
keywords: [octopod, podcast, magic]
itunes_categories: [Technology]
episodes_per_feed_page: 100
# additional_feeds:
#   itunes: http://itunes.apple.com/de/podcast/podcast_name/id42424242
#   torrent_m4a: http://bitlove.org/example_user/example_podcast_m4a/feed
#   torrent_mp3: http://bitlove.org/example_user/example_podcast_mp3/feed
## podlove-web-palyer ##########################################################
poster: /img/logo-360x360.png
alwaysShowHours: true
startVolume: 0.8
width: auto
summaryVisible: false
timecontrolsVisible: false
chaptersVisible: true
sharebuttonsVisible: false
## Rsync Deploy config #########################################################
### Be sure your public key is listed in your server's ~/.ssh/authorized_keys
### file.
ssh_host: user@host.org
ssh_port: 22
document_root: /path/to/your/htdocs/
rsync_delete: true
# You can configure this #######################################################
twitter_nick: jekyll_octopod
language: en
explicit: 'no'  # 'yes'/'no'/clean
license: CC BY 4.0
## Flattr ######################################################################
flattr_uid: # Flattr will not be used unless this is set
flattr_button: compact # compact | default
flattr_mode: auto # auto | manual(default)
flattr_popout:  1 # 1 | 0 (show popout when hovering mouse over button)
flattr_language: en_GB # available languages - https://api.flattr.com/rest/v2/languages.txt
flattr_category: audio # available categories - https://api.flattr.com/rest/v2/categories.txt
## Disqus comments #############################################################
disqus_shortname: # Disqus will not be used unless this is set
disqus_developer: 0 # 1 / 0
## Itunes link ###########################################################
itunes_url: "https://itunes.apple.com/at/podcast/myname/id#myid#"
theme: jekyll-bootflat
plugins: [jekyll-admin]

**Comment by haslinger** [comment]
Then why don't you just use the  jekyll-octopod.github.io repo???

**Comment by haslinger** [comment]
If your insist in using the aua-uff-code repo, I fixed and updated ruby and jekyll versions there as well, but it will be a lot more work for you to remove all configuration changes and overwrites there.

**Comment by ghost** [comment]
thanks, I just wanted to figure out why it wasnt working since I started with that repo, thanks
