### ISSUE TITLE
octopod not rendering on github

### ISSUE THREAD

**Issue by ghost** [jekyll-octopod/jekyll-octopod#51]
I uploaded the _site to github and this is how it looks like, what am I missing ?, I built it locally and pushed _site folder

![capture](https://user-images.githubusercontent.com/37252212/43688983-7d88a102-98b0-11e8-8236-3abd8edec516.PNG)

**Comment by haslinger** [comment]
The assets were not loaded properly.
Have a look in the code inspector of your browser! The error messages should tell you more.
A screenshot of the site doesn't really tell me a lot. Please don't provide screenshots, but rather a link to the site or the repo of the source code.

Maybe you didn't upload all the files, maybe the url parameter in the config file is not correct.
Did you it change it to the github pages domain https://yourrepo.github.io before building?

**Comment by Rafael-Git** [comment]
https://rafael-git.github.io/

https://github.com/Rafael-Git/rafael-git.github.io

**Comment by ghost** [comment]
https://rafael-git.github.io/

https://github.com/Rafael-Git/rafael-git.github.io



![image](https://user-images.githubusercontent.com/42122939/43690745-baba57e8-98cc-11e8-86ca-276a483f5ae1.png)

**Comment by ghost** [comment]
what do I have to change for jekyll to generate the _site with the repo URL? and not with the localhost URL

**Comment by haslinger** [comment]
https://jekyllrb.com/docs/usage/#override-default-development-settings

**Comment by ghost** [comment]
so Github cant generate the site naively?, is uploading the _site folder the only way to use gh-pages?

**Comment by haslinger** [comment]
Yes, as I answered you already in https://github.com/jekyll-octopod/jekyll-octopod/issues/50#issuecomment-410537584.
