### ISSUE TITLE
audio files

### ISSUE THREAD

**Issue by ghost** [jekyll-octopod/jekyll-octopod#54]
hello haslinger,

can i call the audio files from another server?, to use another location as file storage

**Comment by haslinger** [comment]
Yes, with the download_url variable in `_config.yml`:
```
# needed, if and only if audio files are hosted in a different location
download_url: http://my.cdn.com/path/to/episodes/
```

**Comment by ghost** [comment]
thanks, also how can I change the colour on the top menu bar?, it's currently green

**Comment by haslinger** [comment]
Have a look at `_sass/_overrides.scss` in your project: You will find the changes necessary for the six colors used in the navbar in comments.

**Comment by Rafael-Guzman** [comment]
thanks, I was able to do it, can I also change the color of the subscribe button?, is that done in another file?
