### ISSUE TITLE
subscribe button color

### ISSUE THREAD

**Issue by ghost** [jekyll-octopod/jekyll-octopod#55]
Hello, 

I'm trying to find the css to change the subscribe button color, where can I find it?

Thanks !

**Comment by haslinger** [comment]
https://github.com/jekyll-octopod/jekyll-octopod/blob/master/assets/subscribe-button/stylesheets/app.css

**Comment by ghost** [comment]
isnt here where it should be changed?

  <script class="podlove-subscribe-button"
          src="/subscribe-button/javascripts/app.js"
          data-language="{{ site.language }}"
          data-size="medium auto"
          data-style="filled"
          data-json-data="podcastData"
          data-colors="#9951fc;green;blue">
  </script>

**Comment by haslinger** [comment]
You asked for the location of the css for the button, which I gave to you ...
Change whatever you like, whereever you like. It's open source and free software.
