### ISSUE TITLE
jekyll octopod snipcart

### ISSUE THREAD

**Issue by ghost** [jekyll-octopod/jekyll-octopod#56]
Hello Haslinger, 

has anyone looked into snipcart ? what if we wanted to integrate snipcart to octopod and add a donation button or buy button to purchase an episode instead of downloading them?, would this be difficult to achieve ?, I couldnt find the head.html file to add scripts, where can I find it ?

Regards,

**Comment by haslinger** [comment]
I do not provide support for commercial extensions of jekyll-octopod whatsoever.

**Comment by ghost** [comment]
oh okay
