### ISSUE TITLE
not playing audio 

### ISSUE THREAD

**Issue by ghost** [jekyll-octopod/jekyll-octopod#57]
hello, 

I'm trying to figure out why mine doesnt play the audio back, is it supposed to work by default ?

https://assets.guzmanrafael.com//2018/08/08/episode0.html#ede9fc46

https://github.com/Rafael-Guzman/jekyll-octopod

regards,

**Comment by haslinger** [comment]
Yes, it is supposed to work. It actually helps to read the error message in the developer console of your browser. It will tell you, that the domain, that you configured for the assets, www.assets.guzmanrafael.com, cannot be resolved by any DNS Server.

**Comment by ghost** [comment]
thanks I just fixed it, somehow I changed the download URL and it wasnt written correctly
