### ISSUE TITLE
Feature: Google Podcast Feed

### ISSUE THREAD

**Issue by inetbiz** [jekyll-octopod/jekyll-octopod#60]
Read https://support.google.com/googleplay/podcasts/answer/6260341?hl=en

**Comment by haslinger** [comment]
PR's welcome.

**Comment by inetbiz** [comment]
@haslinger 
I'm looking at https://github.com/jekyll-octopod/jekyll-octopod/blob/master/assets/_includes/sidebar.html#L71 To play on google play. I see https://github.com/jekyll-octopod/jekyll-octopod/blob/master/assets/_layouts/feed.xml is specific and doesn't include google podcast tags. A full example of Google Podcast feed can be found at https://support.google.com/googleplay/podcasts/answer/6260341?hl=en and just unsure if adding their tags into yours would block itunes feed or not?

If I make a PR, I'd need a beta tester to install that branch and submit to google podcast before merged?

**Comment by inetbiz** [comment]
I think you can get away with ```<rss xmlns:googleplay="http://www.google.com/schemas/play-podcasts/1.0" version="2.0">``` as google accepts all the itunes fields.

**Comment by inetbiz** [comment]
The only thing I see missing from google's doc is ```<enclosure url="http://sample.com/podcasts/UnknownPodcastEpisode1.mp3" length="2320111" type="audio/mpeg" />``` Couldn't find that at https://github.com/jekyll-octopod/jekyll-octopod/blob/master/assets/_layouts/feed.xml

**Comment by haslinger** [comment]
Typically iTtunes does not have problems with extra tags. If they would, I would obviously remove the interfering tags, as all users need their podcast having submitted to iTunes.
I would never check with Google podcasts, so I would trust your work and depend on it. Also, if other users come up with issues regarding Google podcasts, I would assign them to you. I also won't look in the Google podcasts docs, as I am not interested in submitting my podcasts there.

**Comment by haslinger** [comment]
Seems obsolete.

**Comment by dellagustin** [comment]
Just an extra FYI here, it seems google podcasts (https://podcasts.google.com/) will currently index your feed from a `<link rel="alternate" type="application/rss+xml" href="<your feed url>" title="<your feed title>" />` tag.

Source here: https://developers.google.com/search/docs/guides/podcast-guidelines?hl=en

I am not sure if the same applies to Google Play Music Podcast Portal (https://play.google.com/music/podcasts/portal), I don't have access there as it is not available in my country.

My podcast was indexed just fine, but it took maybe a week, for some weird reason, even though I explicitly triggered indexing from the Google Search Console (https://search.google.com/search-console), so I can confirm that at least for this context, the extra google tags are not mandatory.
