### ISSUE TITLE
Question: Going Live?

### ISSUE THREAD

**Issue by jvkrakowski** [jekyll-octopod/jekyll-octopod#61]
Can we go live with this podcast plugin? If not, is there a way to integrate this feature?

**Comment by haslinger** [comment]
Not sure, if I understand your questions correctly.
You might have seen, we are on Version 0.9.12. According to semantic versioning this is a beta.
On integrating, we are using [MIT](https://github.com/jekyll-octopod/jekyll-octopod/blob/master/LICENSE) license. Follow the link for details.

**Comment by jvkrakowski** [comment]
Going live means that I would record and broadcast at the same time. People can call in, talk to me and it would upload as a recording after the show.

**Comment by haslinger** [comment]
Jekyll-Octopod is neither audio recording software nor audio broadcasting software. 
Both neither were nor will be scope of this project.
It's podcast publishing software. A podcast is audio files distributed via RSS feeds.

As it is open source software, you can fork it and implement it yourself.
