### ISSUE TITLE
no implicit conversion of Hash into String in /_layouts/with_twitter_card.html

### ISSUE THREAD

**Issue by bsde1234** [jekyll-octopod/jekyll-octopod#62]
When I issue `octopod serve` I get `no implicit conversion of Hash into String in /_layouts/with_twitter_card.html` error.

**Comment by haslinger** [comment]
Which versions of Ruby, Jekyll and jekyll-octopod are you using?

**Comment by haslinger** [comment]
Unfortunately no user feedback, so I'll close that for now.
