### ISSUE TITLE
Bundle requires old version of mercenary

### ISSUE THREAD

**Issue by chetwisniewski** [jekyll-octopod/jekyll-octopod#72]
When I updated my ruby I started getting the following error:

.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:312:in `check_for_activated_spec!': You have already activated mercenary 0.4.0, but your Gemfile requires mercenary 0.3.6. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)

**Comment by haslinger** [comment]
Sure. Where's the issue? (The error message itself tells you the solution to this.)

**Comment by chetwisniewski** [comment]
I am not sure I understand. The issue is that I am getting ruby errors when using build or serve commands as per above. It looks like it needs to be updated to support mercenary 0.4? I am inexperienced with Ruby apps, perhaps I am misunderstanding something?

**Comment by haslinger** [comment]
No, the error message just points out the conflict between the installed version of mercenary and the required one. Mercenary is a Jekyll dependency, it is not a Jekyll-Octopod dependency, so if you have issues updating Mercenary, the Jekyll-Octopod Github Repo is not the place to go.
 
I believe, you haven't reinstalled all the Gems that are needed. Please have a look at your Ruby version manager documentation or your Ruby distribution on how to update and reinstall the dependencies. The update process, i.e. reinstalling of all the Gems, that are required, is dependent on the operating system, the Ruby distribution and/or the Ruby Version manager. Maybe it's just `bundle install`, maybe it isn't. There is no dependency to Jekyll-Octopod whatsoever and I am not able to give support besides issues of Jekyll-Octopod. 
Btw. Jekyll-Octopod is not an app. It's an add-on to a static site generator.
