### ISSUE TITLE
uninitialized constant FileUtils

### ISSUE THREAD

**Issue by funkenstrahlen** [jekyll-octopod/jekyll-octopod#9]
when running `octopod setup` I see this:

```
===== Creating a backup of the configuration file ... =====
/Users/funkenstrahlen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-octopod-0.6.5/bin/octopod:242:in `<top (required)>': uninitialized constant FileUtils (NameError)
Did you mean?  FileTest
    from /Users/funkenstrahlen/.rbenv/versions/2.3.1/bin/octopod:23:in `load'
    from /Users/funkenstrahlen/.rbenv/versions/2.3.1/bin/octopod:23:in `<main>'
```

Missing `require`?

**Comment by haslinger** [comment]
FileUtils is part of the standard library, so I guess not.
Your paths look a bit weired, first 2.3.1 then 2.3.0 (Is this normal for rben? I have only experience with rvm).

**Comment by funkenstrahlen** [comment]
This is common with rbenv but I also can not tell you why they do it like this with the versions.

I found this thread: https://github.com/yeahrb/yeah/issues/9 So I guessed maybe adding a require might help.

**Comment by haslinger** [comment]
Let's try. I pushed a new version with a require. (bundle update ... )

**Comment by funkenstrahlen** [comment]
works fine now. thank you!
